# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff6411a9fdac5d5cb55646311322e73165801a68bc2b7739bdcfa2a3cc58d95df8bb7e6406258c24e59f6efc8617656099ca22d489e19c1cac6250e785f519c5

test:
  secret_key_base: b01a35a914ae644ed4bd4b2ac53877237ed555b537461dd1851a2180db267142a0e332fe7c3c388af8cd6ee9527110667f109ebb8fa1097fb29ff972fe0ffa70

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
